### ISSUE TITLE
Parsed ts dosen't have description when string array with description

### ISSUE THREAD

**Issue by GrangbelrLurain** [bcherny/json-schema-to-typescript#660]
I write string array schema with description, but it isn't in parsed typescript.
please update typescript with description.
if you not have time to update, please comment to me for push request this issue.

this is example for this issue, yaml json schema

```yaml
$schema: http://json-schema.org/draft-07/schema#

title: peoples
type: array
description: |
  @group Shared/QueryString
  @description <adult>,<child age>|<child age>
items:
  type: string
  description: |
    @group Shared/QueryString/REGEXP
    @description travel peoples QueryString(<adult>,<child age>|<child age>|...)
  pattern: "^\\d+,(?:\\d+)(?:-\\d+)*$"
  examples:
    - "2,5-7"
    - "1,3-4-5"

```

this is parsed schema to typescript
```ts

/**
 * @group Shared/QueryString
 * @description <adult>,<child age>|<child age>
 */
export type Peoples = string[];
```
